### ISSUE TITLE
Autocomplete for .mjs files (and it's exports) not working

### ISSUE THREAD

**Issue by mxrsoon** [stealify/typescript#2]
The server is not properly providing autocomplete for the exports of .mjs files when using top-level imports.

Here's an example:
At logging/index.mjs I have an export called disable, and it's a function:
![image](https://user-images.githubusercontent.com/49368302/90214209-27442400-ddce-11ea-93a7-16d420fa8145.png)

At parser/index.mjs, I tried to import it, but autocomplete does not show it as a function:
![image](https://user-images.githubusercontent.com/49368302/90214036-b8ff6180-ddcd-11ea-9e94-f24f1d96e5b7.png)

Also, when writing the import, it doesn't suggest .mjs files the same way it suggests .js files:
![image](https://user-images.githubusercontent.com/49368302/90214487-04663f80-ddcf-11ea-97c7-b8a7abdc5eca.png)
(index and disable are .mjs files, test is a .js file)

**Comment by frank-dspeed** [comment]
@wazybr you did something wrong then for me the autocomplet worked but your right it does not show the declarations.

**Comment by mxrsoon** [comment]
I followed the steps in README.md.
Installed your version of the TS server globally using npm, and set "typescript.tsdk" to the lib folder of your package (that was installed in the global node_modules folder).

VSCode recognizes it and outputs:
`Using tsserver from: <node_modules_path>/vscode-typescript/lib/tsserver.js`

**Comment by mxrsoon** [comment]
Aside from that, my package.json has no type attribute set, and my package is made of a mix of .js (for CJS) and .mjs (for ESM) files.

**Comment by frank-dspeed** [comment]
interristing thanks for testing

**Comment by frank-dspeed** [comment]
@wazybr did you turn AllowJs on inside your workspace or user settings? or in the tsconfig? that is also importent

**Comment by mxrsoon** [comment]
@frank-dspeed No, as I'm not using TS compilation. Isn't this supposed to work with JS-only projects as JS completion is provided by TS?

**Comment by frank-dspeed** [comment]
@wazybr This is correct this is designed to work with js only projects also but vscode out of the box does not use the JavaScript features without activating them.

**Comment by frank-dspeed** [comment]
@wazybr install the new version look into this readme
